Separate steps into dependant jobs
It will look better on the actions page.

diff --git a/.github/workflows/merge-queue.yml b/.github/workflows/merge-queue.yml
--- a/.github/workflows/merge-queue.yml
+++ b/.github/workflows/merge-queue.yml
@@ -8,7 +8,7 @@ env:
   PROJECT_REPO: ${{ github.repository }}
 
 jobs:
-  merge:
+  acknowledge:
     runs-on: ubuntu-latest
     steps:
       - name: Acknowledge
@@ -22,12 +22,14 @@ jobs:
               content: 'eyes'
             });
 
+  initialize_git:
+    runs-on: ubuntu-latest
+    steps:
       - name: Set Git user
         run: |
           git config --global user.email "q-bot@jakeprime.com"
           git config --global user.name "Q-bot"
           git config --global pull.ff only
-
 
       # we need 3 git branches:
       #  - the merge queue main repo to read the scripts
@@ -55,190 +57,213 @@ jobs:
           path: project
           fetch-depth: 0
 
+  create_merge_branch:
+    runs-on: ubuntu-latest
+    needs: initialize_git
+    outputs:
+      base_branch: ${{ steps.load_state.outputs.base_branch }}
+      merge_branch: ${{ steps.load_state.outputs.merge_branch }}
+      pr_branch: ${{ steps.load_state.outputs.pr_branch }}
+      sha: ${{ steps.create_merge_branch.outputs.sha }}
+    steps:
+    - name: Lock merge queue state
+      run: merge-queue-repo/.github/scripts/lock-merge-queue-state.sh
 
-      - name: Lock merge queue state
-        run: merge-queue-repo/.github/scripts/lock-merge-queue-state.sh
+    - name: Load merge state
+      id: load_state
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        set -euo pipefail
 
-      - name: Load merge state
-        id: load_state
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          set -euo pipefail
+        cd $GITHUB_WORKSPACE/merge-queue-state
 
-          cd $GITHUB_WORKSPACE/merge-queue-state
+        cat state.json
 
-          cat state.json
+        branch_counter=$(jq '.branchCounter' state.json)
+        branch_counter=$(($branch_counter + 1))
 
-          branch_counter=$(jq '.branchCounter' state.json)
-          branch_counter=$(($branch_counter + 1))
+        pr_url="${{ github.event.issue.pull_request.url }}"
+        pr_branch=$(gh api "$pr_url" --jq .head.ref)
 
-          pr_url="${{ github.event.issue.pull_request.url }}"
-          pr_branch=$(gh api "$pr_url" --jq .head.ref)
+        base_branch=$(jq -r '.mergeBranches | max_by(.count) | .name' state.json)
+        if [[ "$base_branch" == "null" ]]; then
+          base_branch=main
+        fi
 
-          base_branch=$(jq -r '.mergeBranches | max_by(.count) | .name' state.json)
-          if [[ "$base_branch" == "null" ]]; then
-            base_branch=main
-          fi
+        echo "branch_counter=$branch_counter" >> "$GITHUB_OUTPUT"
+        echo "merge_branch=merge-branch-$branch_counter" >> "$GITHUB_OUTPUT"
+        echo "pr_branch=$pr_branch" >> "$GITHUB_OUTPUT"
+        echo "base_branch=$base_branch" >> "$GITHUB_OUTPUT"
 
-          echo "branch_counter=$branch_counter" >> "$GITHUB_OUTPUT"
-          echo "merge_branch=merge-branch-$branch_counter" >> "$GITHUB_OUTPUT"
-          echo "pr_branch=$pr_branch" >> "$GITHUB_OUTPUT"
-          echo "base_branch=$base_branch" >> "$GITHUB_OUTPUT"
+        cat "$GITHUB_OUTPUT"
 
-          cat "$GITHUB_OUTPUT"
+    - name: Create merge branch
+      id: create_merge_branch
+      run: |
+        set -euo pipefail
 
-      - name: Create merge branch
-        id: create_merge_branch
-        run: |
-          set -euo pipefail
+        branch_counter=${{ steps.load_state.outputs.branch_counter }}
+        base_branch=${{ steps.load_state.outputs.base_branch }}
+        merge_branch=${{ steps.load_state.outputs.merge_branch }}
+        pr_branch=${{ steps.load_state.outputs.pr_branch }}
 
-          branch_counter=${{ steps.load_state.outputs.branch_counter }}
-          base_branch=${{ steps.load_state.outputs.base_branch }}
-          merge_branch=${{ steps.load_state.outputs.merge_branch }}
-          pr_branch=${{ steps.load_state.outputs.pr_branch }}
+        cd $GITHUB_WORKSPACE/project
 
-          cd $GITHUB_WORKSPACE/project
+        git fetch origin $base_branch $pr_branch
 
-          git fetch origin $base_branch $pr_branch
-          # git fetch origin $base_branch $pr_branch --unshallow
+        git checkout $base_branch && git pull
+        git checkout -b $merge_branch
 
-          git checkout $base_branch && git pull
-          git checkout -b $merge_branch
+        git checkout $pr_branch && git pull
+        git rebase $merge_branch
 
-          git checkout $pr_branch && git pull
-          git rebase $merge_branch
+        git merge --no-edit --no-ff $pr_branch
+        git push --set-upstream origin HEAD:$merge_branch
 
-          git merge --no-edit --no-ff $pr_branch
-          git push --set-upstream origin HEAD:$merge_branch
+        sha=$(git rev-parse --short HEAD)
+        echo "sha=$sha" >> "$GITHUB_OUTPUT"
 
-          sha=$(git rev-parse --short HEAD)
-          echo "sha=$sha" >> "$GITHUB_OUTPUT"
+        cd $GITHUB_WORKSPACE/merge-queue-state
 
-          cd $GITHUB_WORKSPACE/merge-queue-state
+        state="$(cat state.json)"
 
-          state="$(cat state.json)"
+        state="$(echo $state | jq \
+          --arg name "$merge_branch" \
+          --arg sha "$sha" \
+          --arg status "running" \
+          --argjson count $branch_counter \
+          '.mergeBranches += [{
+            name: $name,
+            sha: $sha,
+            status: $status,
+            count: $count
+          }]')"
 
-          state="$(echo $state | jq \
-            --arg name "$merge_branch" \
-            --arg sha "$sha" \
-            --arg status "running" \
-            --argjson count $branch_counter \
-            '.mergeBranches += [{
-              name: $name,
-              sha: $sha,
-              status: $status,
-              count: $count
-            }]')"
+        state="$(echo $state | jq --argjson count $branch_counter '.branchCounter = $count')"
 
-          state="$(echo $state | jq --argjson count $branch_counter '.branchCounter = $count')"
-
-          if [[ -n "$state" ]]; then
-            echo "$state" > state.json
-            git add state.json
-            git commit -m 'Updating merge state'
-            git push
-          fi
-
-      - name: Unlock merge queue state
-        run: merge-queue-repo/.github/scripts/unlock-merge-queue-state.sh
-
-      - name: Wait for CircleCI to pass
-        id: wait_for_ci
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          REPO=${{ github.repository }}
-          SHA=${{ steps.create_merge_branch.outputs.sha }}
-
-          for i in {1..60}; do
-            result=$(gh api repos/$REPO/commits/$SHA/status)
-
-            state=$(echo "$result" | jq -r '.state')
-
-            echo "Status state: $state"
-
-            if [ "$state" = "success" ]; then
-              echo "✅ All statuses passed"
-              exit 0
-            elif [ "$state" = "failure" ]; then
-              echo "❌ One or more statuses failed"
-              exit 1
-            fi
-
-            echo "Waiting for statuses..."
-            sleep 10
-          done
-
-          echo "⏰ Timed out waiting for commit status"
-          exit 1
-
-      - name: Wait until first in queue
-        run: |
-          merge_branch=${{ steps.load_state.outputs.merge_branch }}
-
-          cd $GITHUB_WORKSPACE/merge-queue-state
-
-          for i in {1..12}; do
-            git fetch origin ${{ env.PROJECT_REPO }} --depth 1
-
-            first_branch=$(
-              git show origin/${{ env.PROJECT_REPO }}:state.json |
-              jq -r '.mergeBranches | min_by(.count) | .name'
-            )
-
-            if [[ "$merge_branch" == "$first_branch" ]]; then
-              exit 0
-            fi
-
-            echo "Waiting for queue position"
-            sleep 5
-          done
-
-          echo "⏰ Timed out waiting for queue position"
-          exit 1
-
-      - name: Lock merge queue state
-        run: merge-queue-repo/.github/scripts/lock-merge-queue-state.sh
-
-      - name: Merge to main
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          set -euo pipefail
-
-          base_branch=${{ steps.load_state.outputs.base_branch }}
-          merge_branch=${{ steps.load_state.outputs.merge_branch }}
-          pr_branch=${{ steps.load_state.outputs.pr_branch }}
-
-          cd $GITHUB_WORKSPACE/project
-
-          git fetch origin main $pr_branch
-          git checkout $pr_branch && git pull
-          git rebase origin/main
-          git push --force-with-lease origin HEAD:$pr_branch
-
-          sleep 5
-
-          # gh pr merge ${{ github.event.issue.number }} --merge --delete-branch
-
-          git checkout main && git pull
-          git merge $pr_branch --no-ff
-          git push
-
-          # git push --delete origin $merge_branch
-
-          cd $GITHUB_WORKSPACE/merge-queue-state
-
-          cat state.json
-          jq \
-            --arg name "$merge_branch" \
-            '.mergeBranches |= map(select(.name != $name))' state.json > tmp && mv tmp state.json
+        if [[ -n "$state" ]]; then
+          echo "$state" > state.json
           git add state.json
-          git commit -m '$merge_branch has been successfully merged'
+          git commit -m 'Updating merge state'
           git push
+        fi
 
-          cat state.json
+    - name: Unlock merge queue state
+      run: merge-queue-repo/.github/scripts/unlock-merge-queue-state.sh
 
-      - name: Unlock merge queue state
-        run: merge-queue-repo/.github/scripts/unlock-merge-queue-state.sh
+  wait_for_ci:
+    runs-on: ubuntu-latest
+    needs: create_merge_branch
+    outputs:
+      base_branch: ${{ steps.load_state.outputs.base_branch }}
+      merge_branch: ${{ steps.load_state.outputs.merge_branch }}
+      pr_branch: ${{ steps.load_state.outputs.pr_branch }}
+    steps:
+    - name: Wait for CircleCI to pass
+      id: wait_for_ci
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        REPO=${{ github.repository }}
+        SHA=${{ needs.create_merge_branch.outputs.sha }}
+
+        for i in {1..60}; do
+          result=$(gh api repos/$REPO/commits/$SHA/status)
+
+          state=$(echo "$result" | jq -r '.state')
+
+          echo "Status state: $state"
+
+          if [ "$state" = "success" ]; then
+            echo "✅ All statuses passed"
+            exit 0
+          elif [ "$state" = "failure" ]; then
+            echo "❌ One or more statuses failed"
+            exit 1
+          fi
+
+          echo "Waiting for statuses..."
+          sleep 10
+        done
+
+        echo "⏰ Timed out waiting for commit status"
+        exit 1
+
+  wait_in_queue:
+    runs-on: ubuntu-latest
+    needs: [create_merge_branch, wait_for_ci]
+    steps:
+    - name: Wait until first in queue
+      run: |
+        merge_branch=${{ needs.create_merge_branch.outputs.merge_branch }}
+
+        cd $GITHUB_WORKSPACE/merge-queue-state
+
+        for i in {1..12}; do
+          git fetch origin ${{ env.PROJECT_REPO }} --depth 1
+
+          first_branch=$(
+            git show origin/${{ env.PROJECT_REPO }}:state.json |
+            jq -r '.mergeBranches | min_by(.count) | .name'
+          )
+
+          if [[ "$merge_branch" == "$first_branch" ]]; then
+            exit 0
+          fi
+
+          echo "Waiting for queue position"
+          sleep 5
+        done
+
+        echo "⏰ Timed out waiting for queue position"
+        exit 1
+
+  merge_branch:
+    runs-on: ubuntu-latest
+    needs: [create_merge_branch, wait_in_queue]
+    steps:
+    - name: Lock merge queue state
+      run: merge-queue-repo/.github/scripts/lock-merge-queue-state.sh
+
+    - name: Merge to main
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        set -euo pipefail
+
+        base_branch=${{ needs.create_merge_branch.outputs.base_branch }}
+        merge_branch=${{ needs.create_merge_branch.outputs.merge_branch }}
+        pr_branch=${{ needs.create_merge_branch.outputs.pr_branch }}
+
+        cd $GITHUB_WORKSPACE/project
+
+        git fetch origin main $pr_branch
+        git checkout $pr_branch && git pull
+        git rebase origin/main
+        git push --force-with-lease origin HEAD:$pr_branch
+
+        sleep 5
+
+        # gh pr merge ${{ github.event.issue.number }} --merge --delete-branch
+
+        git checkout main && git pull
+        git merge $pr_branch --no-ff
+        git push
+
+        # git push --delete origin $merge_branch
+
+        cd $GITHUB_WORKSPACE/merge-queue-state
+
+        cat state.json
+        jq \
+          --arg name "$merge_branch" \
+          '.mergeBranches |= map(select(.name != $name))' state.json > tmp && mv tmp state.json
+        git add state.json
+        git commit -m '$merge_branch has been successfully merged'
+        git push
+
+        cat state.json
+
+    - name: Unlock merge queue state
+      run: merge-queue-repo/.github/scripts/unlock-merge-queue-state.sh
